# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c96a9d1f846abe6af394636d36f34c93fc29f9dca48b99bc09ca2189473478b43853adb69faf773d6414f4eb9423df677db918ed0e7c3680f961c35e4ef7b6e

test:
  secret_key_base: 570d9e357154972bf0583cec8d7499eee8b4d9735a4b0363f862d410f488e19d979d0ca6f3ee2c0e2a429381c0671e57a14f7b9d03dfa1281e6c32957212e1ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
